<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>FortuneForge.Server.LocalDevelopment</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
    <PackageReference Include="FortuneForge.Games.Blackjack" Version="0.4.1" />
    <PackageReference Include="FortuneForge.Games.Solitaire" Version="0.4.1" />
    <PackageReference Include="FortuneForge.Games.TexasHoldem" Version="0.4.1" />
    <PackageReference Include="Google.Cloud.Firestore" Version="4.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="FortuneForge.Games.Blackjack" />
    <Using Include="FortuneForge.Games.Cards" />
    <Using Include="FortuneForge.Games.Solitaire" />
    <Using Include="FortuneForge.Games.TexasHoldem" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FortuneForge.ServiceDefaults\FortuneForge.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>FortuneForge.Server.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
