import { mkdir, copyFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { expect, test, type Page, type TestInfo } from '@playwright/test'
import type { CrapsExtraBet, CrapsExtraBetRequest, CrapsRollResult, CrapsRound, CrapsStatus } from '../../../games/Craps/client/FortuneForge.Games.Craps.Client/src/contracts'
const status: CrapsStatus = { available:true,minimumStake:1,maximumStake:100,stakeIncrement:1,mode:'free-play-pass-line' }
const viewports=[{name:'desktop',width:1280,height:720},{name:'phone',width:390,height:844},{name:'short-phone',width:390,height:700},{name:'compact-phone',width:320,height:568},{name:'narrow-landscape',width:500,height:320},{name:'small-landscape',width:568,height:320},{name:'landscape',width:667,height:375},{name:'wide-landscape',width:852,height:393}]
const action=(page:Page)=>page.locator('.ff-craps-primary')
for(const viewport of viewports) test('Craps '+viewport.name+' keeps the table, working bets and action stable',async({page},info)=>{
  await page.setViewportSize(viewport); const fixture=await mockCraps(page); await page.goto('/games/craps'); await expect(action(page)).toBeEnabled(); await page.evaluate(()=>document.fonts.ready)
  await fits(page); await capture(page,info,viewport.name+'-idle'); const board=await page.locator('.ff-craps-table__felt').boundingBox(),rail=await action(page).boundingBox()
  await page.getByRole('button',{name:/^Field,/}).click(); await expect(page.locator('.ff-craps-bet-marker')).toHaveText('R5'); await expect(page.locator('.ff-craps-summary')).toContainText('R15.00'); await capture(page,info,viewport.name+'-draft')
  await action(page).click(); await expect(action(page)).toHaveText('Roll come-out'); expect(fixture.writes[0].body).toEqual({stake:10,extraBets:[{kind:'field',stake:5}]}); await fits(page); await capture(page,info,viewport.name+'-come-out')
  await action(page).click(); await expect(action(page)).toHaveText('Roll point 4'); await expect(page.locator('.ff-craps-point-row .is-on')).toHaveText('ON'); await expect(page.locator('.ff-craps-proposition.is-win')).toContainText('Returned R10.00'); await expect(page.locator('.ff-craps-summary')).toContainText('R10.00'); await fits(page); await capture(page,info,viewport.name+'-point')
  await page.getByRole('button',{name:'Add odds',exact:true}).click(); await page.getByRole('spinbutton',{name:'Pass Line odds stake'}).fill('1'); await fitsPanel(page); await capture(page,info,viewport.name+'-odds-panel'); await page.getByRole('button',{name:'Place odds',exact:true}).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.locator('.ff-craps-pass-line')).toContainText('Odds R1.00'); await fits(page); await capture(page,info,viewport.name+'-odds')
  await action(page).click(); await expect(action(page)).toHaveText('Roll point 4'); await expect(page.getByRole('status')).toContainText('9 rolled'); await capture(page,info,viewport.name+'-hold')
  await action(page).click(); await expect(action(page)).toHaveText(/^Repeat R/); await expect(page.locator('.ff-craps-summary')).toContainText('Total return R33.00'); await expect(page.getByRole('status')).toContainText('Net +R17.00'); await expect(page.locator('.ff-craps-point-row .is-on')).toHaveCount(0); await expect(page.locator('.ff-craps-pass-line')).not.toHaveClass(/has-bet/); await expect(page.locator('.ff-craps-bet-marker')).toHaveCount(0); await fits(page); expect(await page.locator('.ff-craps-table__felt').boundingBox()).toEqual(board); expect(await action(page).boundingBox()).toEqual(rail); await capture(page,info,viewport.name+'-point-made')
  await page.getByRole('button',{name:'Bets',exact:true}).click(); await expect(page.getByRole('dialog')).toContainText('Pass OddsR1.00Returned R3.00'); await fitsPanel(page); await capture(page,info,viewport.name+'-settlement'); await page.keyboard.press('Escape'); await expect(page.getByRole('button',{name:'Bets',exact:true})).toBeFocused()
  await action(page).click(); await expect(action(page)).toHaveText('Roll come-out'); expect(fixture.round!.extraBets).toEqual([{kind:'field',stake:5,resolved:false,won:false,totalReturn:null}]); await capture(page,info,viewport.name+'-repeat')
  fixture.sequence=[[1,6]]; await action(page).click(); await expect(action(page)).toHaveText(/^Repeat R/); await page.getByRole('button',{name:'Edit bet',exact:true}).click(); await expect(page.getByRole('spinbutton',{name:'Pass Line bet in Rand'})).toHaveValue('10'); await expect(page.getByRole('button',{name:/^Field,/})).toHaveAttribute('aria-pressed','true'); await fits(page); await capture(page,info,viewport.name+'-edit')
  await page.getByRole('button',{name:'Tips',exact:true}).click(); await expect(page.getByRole('dialog')).toContainText('6:5'); await expect(page.getByRole('dialog')).not.toContainText('Preview scope'); await fitsPanel(page); await capture(page,info,viewport.name+'-tips'); await page.keyboard.press('Escape'); await expect(page.getByRole('button',{name:'Tips',exact:true})).toBeFocused()
})
for(const sample of [{name:'natural-seven',pair:[1,6],returned:45,net:20,label:'Natural 7'},{name:'craps-two',pair:[1,1],returned:55,net:30,label:'Craps 2'},{name:'natural-eleven',pair:[5,6],returned:30,net:5,label:'Natural 11'},{name:'craps-twelve',pair:[6,6],returned:55,net:30,label:'Craps 12'}]) test('Craps '+sample.name+' shows aggregate authoritative settlement',async({page},info)=>{
  const fixture=await mockCraps(page); fixture.sequence=[sample.pair]; await page.goto('/games/craps'); for(const name of ['Field','Any Seven','Any Craps'])await page.getByRole('button',{name:new RegExp('^'+name+',')}).click(); await action(page).click(); await expect(action(page)).toHaveText('Roll come-out'); await action(page).click(); await expect(action(page)).toHaveText(/^Repeat R/); await expect(page.getByRole('status')).toContainText(sample.label); await expect(page.locator('.ff-craps-summary')).toContainText('Total return R'+sample.returned.toFixed(2)); await expect(page.getByRole('status')).toContainText('Net +R'+sample.net.toFixed(2)); await capture(page,info,sample.name)
})
test('Craps point six accepts whole odds and displays fractional server return, then seven-out',async({page},info)=>{
 const fixture=await mockCraps(page);fixture.sequence=[[3,3],[2,4]];await page.goto('/games/craps');await action(page).click();await action(page).click();await expect(action(page)).toHaveText('Roll point 6');await page.getByRole('button',{name:'Add odds',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Pays 6:5');await page.getByRole('spinbutton',{name:'Pass Line odds stake'}).fill('1');await page.getByRole('button',{name:'Place odds',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await action(page).click();await expect(action(page)).toHaveText(/^Repeat R/);await expect(page.locator('.ff-craps-summary')).toContainText('R22.20');await expect(page.getByRole('status')).toContainText('Net +R11.20');await capture(page,info,'point-six-fractional-odds');await action(page).click();await expect(action(page)).toHaveText('Roll come-out');fixture.sequence=[[2,3],[1,6]];await action(page).click();await expect(action(page)).toHaveText('Roll point 5');await action(page).click();await expect(action(page)).toHaveText(/^Repeat R/);await expect(page.getByRole('status')).toContainText('Seven-out');await expect(page.getByRole('status')).toContainText('−R10.00');await capture(page,info,'seven-out')
})
test('Craps exact drafts, legal chips and disabled status do not silently change wagers',async({page},info)=>{
 const fixture=await mockCraps(page,{...status,minimumStake:7.5,maximumStake:12.5,stakeIncrement:2.5});await page.goto('/games/craps');await expect(action(page)).toBeEnabled();await expect(page.locator('.ff-craps-chip-row button')).toHaveText(['R7.5','R10','R12.5']);for(const value of ['','0','7','10.5','13']){await page.getByRole('spinbutton',{name:'Pass Line bet in Rand'}).fill(value);await expect(action(page)).toBeDisabled()};await page.getByRole('spinbutton',{name:'Pass Line bet in Rand'}).fill('12.5');await page.getByRole('button',{name:/^Field,/}).click();await expect(action(page)).toBeDisabled();await page.getByRole('spinbutton',{name:'Each one-roll bet in Rand'}).fill('7.5');await expect(action(page)).toBeEnabled();await capture(page,info,'exact-limits');await action(page).click();await expect(action(page)).toHaveText('Roll come-out');expect(fixture.writes[0].body).toEqual({stake:12.5,extraBets:[{kind:'field',stake:7.5}]});fixture.tableStatus.available=false;await page.reload();await expect(action(page)).toBeDisabled();await expect(page.getByRole('alert')).toContainText('temporarily unavailable');await capture(page,info,'unavailable')
})
test('Craps uncertain roll and odds responses read the accepted hand without replay, including reload',async({page},info)=>{
 const fixture=await mockCraps(page);await page.goto('/games/craps');await action(page).click();await expect(action(page)).toHaveText('Roll come-out');fixture.failNextRoll=true;await action(page).click();await expect(action(page)).toHaveText('Roll point 4');await expect(page.getByRole('alert')).toContainText('Hand refreshed');expect(fixture.writes.filter(value=>value.path.endsWith('/roll'))).toHaveLength(1);await capture(page,info,'lost-roll-restored');await page.getByRole('button',{name:'Add odds',exact:true}).click();fixture.failNextOdds=true;await page.getByRole('button',{name:'Place odds',exact:true}).click();await expect(page.locator('.ff-craps-pass-line')).toContainText('Odds R10.00');expect(fixture.writes.filter(value=>value.path.endsWith('/odds'))).toHaveLength(1);await capture(page,info,'lost-odds-restored');await page.reload();await expect(action(page)).toHaveText('Roll point 4');await expect(page.locator('.ff-craps-pass-line')).toContainText('Odds R10.00');expect(fixture.writes.filter(value=>value.path.endsWith('/rounds'))).toHaveLength(1);await capture(page,info,'reload-working')
})
test('Craps failed reads lock writes until restoration and missing hands expire safely',async({page},info)=>{
 const fixture=await mockCraps(page);await page.goto('/games/craps');await action(page).click();await expect(action(page)).toHaveText('Roll come-out');fixture.failNextRoll=true;fixture.failReads=true;await action(page).click();await expect(page.getByRole('alert')).toContainText('could not be restored');await expect(action(page)).toBeDisabled();await capture(page,info,'restoration-locked');fixture.failReads=false;await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(action(page)).toHaveText('Roll point 4');expect(fixture.writes.filter(value=>value.path.endsWith('/roll'))).toHaveLength(1);await capture(page,info,'restoration-retry');fixture.round=null;await page.reload();await expect(action(page)).toBeEnabled();await expect(page.getByRole('alert')).toContainText('expired');await capture(page,info,'expired-hand')
})
test('Craps unknown start response is transparent and does not automatically replay',async({page},info)=>{
 const fixture=await mockCraps(page);await page.goto('/games/craps');fixture.failNextStart=true;await action(page).click();await expect(page.getByRole('alert')).toContainText('Bet response lost');await expect(action(page)).toBeEnabled();expect(fixture.writes.filter(value=>value.path.endsWith('/rounds'))).toHaveLength(1);await capture(page,info,'lost-start-unknown')
})
test('Craps restoring mixed and duplicate extras preserves exact edit and repeat payloads',async({page},info)=>{
 const fixture=await mockCraps(page);fixture.sequence=[[1,6]];await page.goto('/games/craps');await action(page).click();await expect(action(page)).toHaveText('Roll come-out');fixture.round={...fixture.round!,extraBets:[{kind:'field',stake:5,resolved:false,won:false,totalReturn:null},{kind:'field',stake:10,resolved:false,won:false,totalReturn:null},{kind:'any-seven',stake:2,resolved:false,won:false,totalReturn:null}]};await page.reload();await expect(action(page)).toHaveText('Roll come-out');await action(page).click();await expect(action(page)).toHaveText(/^Repeat R/);await page.getByRole('button',{name:'Edit bet',exact:true}).click();await expect(action(page)).toBeEnabled();await page.getByRole('button',{name:'Bets',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Field R5.00');await expect(page.getByRole('dialog')).toContainText('Field R10.00');await fitsPanel(page);await capture(page,info,'mixed-restored-edit');await page.keyboard.press('Escape');await action(page).click();await expect(action(page)).toHaveText('Roll come-out');expect(fixture.writes.at(-1)!.body).toEqual({stake:10,extraBets:[{kind:'field',stake:5},{kind:'field',stake:10},{kind:'any-seven',stake:2}]})
})
test('Craps touch and keyboard feedback, normal animation and reduced motion remain usable',async({browser},info)=>{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,reducedMotion:'no-preference'});const page=await context.newPage();const fixture=await mockCraps(page);await page.goto('http://127.0.0.1:4177/games/craps');await page.getByRole('button',{name:/^Field,/}).tap();await expect(page.getByRole('button',{name:/^Field,/})).toHaveAttribute('aria-pressed','true');await action(page).tap();await expect(action(page)).toHaveText('Roll come-out');const before=fixture.writes.length;await action(page).focus();await page.keyboard.press('Enter');await expect(page.locator('.ff-craps-dice .ff-die-sprite-frame:not(.is-idle)').first()).toHaveCSS('animation-name','ff-die-course');await expect(action(page)).toBeDisabled();await capture(page,info,'normal-motion-reveal');await expect(action(page)).toHaveText('Roll point 4');expect(fixture.writes.length).toBe(before+1);await expect(action(page)).toBeFocused();await expect(page.locator('.ff-craps-point-row')).toHaveCSS('user-select','none');await page.emulateMedia({reducedMotion:'reduce'});await action(page).tap();await expect(action(page)).toHaveText('Roll point 4');await expect(page.locator('.ff-craps-dice .ff-die-sprite-frame').first()).toHaveCSS('animation-name','none');await capture(page,info,'reduced-motion-hold');await fits(page);await context.close()
})
test('Craps maximum permitted stakes keep all chip labels readable without a combined or wallet cap',async({page},info)=>{ const fixture=await mockCraps(page); await page.goto('/games/craps');await page.getByRole('spinbutton',{name:'Pass Line bet in Rand'}).fill('100');await page.getByRole('spinbutton',{name:'Each one-roll bet in Rand'}).fill('100');for(const name of ['Field','Any Seven','Any Craps'])await page.getByRole('button',{name:new RegExp('^'+name+',')}).click();await expect(page.locator('.ff-craps-bet-marker')).toHaveText(['R100','R100','R100']);await expect(page.locator('.ff-craps-summary')).toContainText('R400.00');for(const viewport of [{width:1280,height:720},{width:320,height:568},{width:500,height:320}]){await page.setViewportSize(viewport);await fits(page);await capture(page,info,'maximum-stakes-'+viewport.width+'x'+viewport.height)};await action(page).click();await expect(action(page)).toHaveText('Roll come-out');expect(fixture.writes[0].body).toEqual({stake:100,extraBets:[{kind:'field',stake:100},{kind:'any-seven',stake:100},{kind:'any-craps',stake:100}]})})
async function fits(page:Page){const geometry=await page.evaluate(()=>({width:innerWidth,height:innerHeight,sw:document.documentElement.scrollWidth,sh:document.documentElement.scrollHeight,boxes:[...document.querySelectorAll('.ff-craps-point-row,.ff-craps-center,.ff-craps-propositions,.ff-craps-pass-line,.ff-craps-controls,.ff-craps-primary')].map(element=>{const b=element.getBoundingClientRect();return{x:b.x,y:b.y,r:b.right,b:b.bottom,w:b.width,h:b.height}})}));expect(geometry.sw).toBeLessThanOrEqual(geometry.width);expect(geometry.sh).toBeLessThanOrEqual(geometry.height);for(const b of geometry.boxes){expect(b.x).toBeGreaterThanOrEqual(0);expect(b.y).toBeGreaterThanOrEqual(0);expect(b.r).toBeLessThanOrEqual(geometry.width+.1);expect(b.b).toBeLessThanOrEqual(geometry.height+.1);expect(b.w).toBeGreaterThan(20);expect(b.h).toBeGreaterThan(10)};for(let i=0;i<3;i++)expect(geometry.boxes[i].b).toBeLessThanOrEqual(geometry.boxes[i+1].y+.1);const button=await action(page).boundingBox();expect(button!.height).toBeGreaterThanOrEqual(40);expect(await action(page).evaluate(element=>{const b=element.getBoundingClientRect();return element.contains(document.elementFromPoint(b.x+b.width/2,b.y+b.height/2))})).toBe(true);const center=await page.locator('.ff-craps-center').boundingBox(),total=await page.locator('.ff-craps-dice__total').boundingBox();expect(total!.y+total!.height).toBeLessThanOrEqual(center!.y+center!.height+.1)}
async function fitsPanel(page:Page){const b=await page.getByRole('dialog').boundingBox(),v=page.viewportSize()!;expect(b!.x).toBeGreaterThanOrEqual(0);expect(b!.y).toBeGreaterThanOrEqual(0);expect(b!.x+b!.width).toBeLessThanOrEqual(v.width);expect(b!.y+b!.height).toBeLessThanOrEqual(v.height);const actionBox=await action(page).boundingBox();expect(b!.y+b!.height).toBeLessThanOrEqual(actionBox!.y)}
async function capture(page:Page,info:TestInfo,name:string){const directory=resolve(process.cwd(),'../.artifacts/ux-cycle/craps');await mkdir(directory,{recursive:true});const path=info.outputPath(name+'.png');await page.screenshot({path});await copyFile(path,resolve(directory,name+'.png'));await info.attach(name,{path,contentType:'image/png'})}
async function mockCraps(page:Page,tableStatus:CrapsStatus={...status}){
 const fixture={round:null as CrapsRound|null,count:0,index:0,sequence:[[2,2],[3,6],[1,3]] as number[][],tableStatus,failNextRoll:false,failNextOdds:false,failNextStart:false,failReads:false,writes:[] as {path:string;body:unknown}[]}
 await page.route('**/api/**',async route=>{
  const req=route.request(),path=new URL(req.url()).pathname,method=req.method(),json=(value:unknown,code=200)=>route.fulfill({status:code,contentType:'application/json',body:JSON.stringify(value)})
  if(path==='/api/accounts/me')return json({userId:'craps-ux-player',playerName:'Alex',email:'alex@example.test',createdAtUtc:'2026-01-01T00:00:00Z',balances:{slotsCredits:1000,freeGames:0},role:'Player',slots:{spinsPlayed:0,wins:0,losses:0,creditsWagered:0,creditsWon:0,netCredits:0}})
  if(path.endsWith('/craps/status'))return json(fixture.tableStatus)
  if(!path.includes('/games/craps/'))return json({})
  if(method!=='GET')fixture.writes.push({path,body:req.postDataJSON()})
  if(path.endsWith('/rounds')&&method==='POST'){const body=req.postDataJSON() as {stake:number;extraBets:CrapsExtraBetRequest[]};fixture.count++;fixture.index=0;fixture.round={roundId:'00000000-0000-4000-8000-'+String(fixture.count).padStart(12,'0'),stake:body.stake,phase:'come-out',point:null,rolls:[],lastOutcome:null,extraBets:body.extraBets.map(bet=>({...bet,resolved:false,won:false,totalReturn:null}))};if(fixture.failNextStart){fixture.failNextStart=false;return route.abort('failed')};return json(fixture.round)}
  if(method==='GET'){if(fixture.failReads)return route.abort('failed');return fixture.round?json(fixture.round):json({code:'craps-round-not-found',message:'Hand expired'},404)}
  const hand=fixture.round;if(!hand)return json({code:'craps-round-not-found',message:'Hand expired'},404)
  if(path.endsWith('/odds')){const body=req.postDataJSON() as {stake:number};fixture.round={...hand,extraBets:[...(hand.extraBets??[]),{kind:'odds',stake:body.stake,resolved:false,won:false,totalReturn:null}]};if(fixture.failNextOdds){fixture.failNextOdds=false;return route.abort('failed')};return json(fixture.round)}
  if(path.endsWith('/roll')){const pair=fixture.sequence[fixture.index++]??[1,6],total=pair[0]+pair[1];const result:CrapsRollResult=hand.phase==='come-out'?([7,11].includes(total)?'natural-win':[2,3,12].includes(total)?'craps-loss':'point-established'):total===hand.point?'point-hit':total===7?'seven-out':'no-decision';const terminal=['natural-win','craps-loss','point-hit','seven-out'].includes(result),won=['natural-win','point-hit'].includes(result);const point=result==='point-established'?total:hand.point;const extras:CrapsExtraBet[]=(hand.extraBets??[]).map(bet=>{if(bet.resolved||bet.kind==='odds'&&!terminal)return bet;const success=bet.kind==='odds'?won:bet.kind==='field'?[2,3,4,9,10,11,12].includes(total):bet.kind==='any-seven'?total===7:[2,3,12].includes(total);const factor=bet.kind==='odds'?point===4||point===10?3:point===5||point===9?2.5:2.2:bet.kind==='field'?[2,12].includes(total)?3:2:bet.kind==='any-seven'?5:8;return{...bet,resolved:true,won:success,totalReturn:success?Math.round(bet.stake*factor*100)/100:0}});fixture.round={...hand,phase:terminal?'resolved':'point',point,rolls:[...hand.rolls.map(roll=>({...roll,result:null})),{rollNumber:hand.rolls.length+1,first:pair[0],second:pair[1],total,result}],lastOutcome:{first:pair[0],second:pair[1],total,result,isTerminal:terminal,totalReturn:terminal?won?hand.stake*2:0:null},extraBets:extras};if(fixture.failNextRoll){fixture.failNextRoll=false;return route.abort('failed')};return json(fixture.round)}
  return json({})
 });return fixture
}
