namespace FortuneForge.Server.Payments.Models;

internal sealed record PaymentCheckoutDraft(
    string UserId,
    string InvoiceId,
    string IdempotencyKey,
    PaymentMarketOption Market,
    PaymentMethodOption PaymentMethod,
    long Amount,
    long AmountMinor,
    long Credits,
    PaymentCustomerDetails Customer,
    PaymentBankDetails PayerBank,
    DateTime CreatedAtUtc,
    DateTime ExpiresAtUtc);

internal sealed record PaymentWithdrawalDraft(
    string UserId,
    string WithdrawalId,
    string IdempotencyKey,
    PaymentMarketOption Market,
    long Amount,
    long AmountMinor,
    long CreditsDebited,
    PaymentCustomerDetails Customer,
    WithdrawalBankDetails Bank,
    DateTime CreatedAtUtc);

internal sealed record StoredPaymentCheckout(
    string CheckoutId,
    string ProviderCheckoutId,
    string? ProviderPathwayKey,
    string InvoiceId,
    string UserId,
    string IdempotencyKey,
    string ProviderId,
    bool IsMock,
    PaymentMarketOption Market,
    PaymentMethodOption PaymentMethod,
    long Amount,
    long AmountMinor,
    long Credits,
    string Status,
    DateTime StatusUpdatedAtUtc,
    DateTime CreatedAtUtc,
    DateTime ExpiresAtUtc,
    DateTime? ProcessingAtUtc,
    DateTime? CompletedAtUtc,
    decimal? CreditedBalance,
    PaymentCustomerDetails Customer,
    PaymentBankDetails PayerBank,
    BankTransferInstructions? BankTransfer,
    string Notice,
    string ProviderSubmissionStatus = "idle",
    string? ProviderSubmissionLeaseId = null,
    DateTime? ProviderSubmissionLeaseUntilUtc = null,
    DateTime? NextProviderSubmissionAtUtc = null,
    DateTime? LastProviderSubmissionAtUtc = null,
    int ProviderSubmissionAttempt = 0,
    int? LastProviderSubmissionStatusCode = null)
{
    public PaymentCheckoutResponse ToResponse() => new(
        CheckoutId,
        ProviderCheckoutId,
        InvoiceId,
        UserId,
        ProviderId,
        IsMock,
        Market.Code,
        Market.DisplayName,
        Market.Currency,
        Market.Locale,
        PaymentMethod.Id,
        PaymentMethod.DisplayName,
        PaymentMethod.Type,
        Amount,
        AmountMinor,
        Credits,
        Status,
        StatusUpdatedAtUtc,
        CreatedAtUtc,
        ExpiresAtUtc,
        ProcessingAtUtc,
        CompletedAtUtc,
        CreditedBalance,
        Customer,
        PayerBank,
        BankTransfer,
        Notice);
}

internal sealed record StoredPaymentWithdrawal(
    string WithdrawalId,
    string ProviderWithdrawalId,
    string? ProviderPathwayKey,
    string UserId,
    string IdempotencyKey,
    string ProviderId,
    bool IsMock,
    PaymentMarketOption Market,
    long Amount,
    long AmountMinor,
    long CreditsDebited,
    string Status,
    DateTime StatusUpdatedAtUtc,
    DateTime CreatedAtUtc,
    DateTime? CompletedAtUtc,
    PaymentCustomerDetails Customer,
    WithdrawalBankDetails Bank,
    string Notice)
{
    public PaymentWithdrawalResponse ToResponse() => new(
        WithdrawalId,
        ProviderWithdrawalId,
        UserId,
        ProviderId,
        IsMock,
        Market.Code,
        Market.DisplayName,
        Market.Currency,
        Market.Locale,
        Amount,
        AmountMinor,
        CreditsDebited,
        Status,
        StatusUpdatedAtUtc,
        CreatedAtUtc,
        CompletedAtUtc,
        Customer,
        Bank,
        Notice);
}
